#!/usr/bin/env python3
"""Render index.html from index.template.html and stats.json."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

TEMPLATE_PATH = Path("index.template.html")
STATS_PATH = Path("stats.json")
OUTPUT_PATH = Path("index.html")
TOKEN_PATTERN = re.compile(r"\{\{stats:([^}|]+)(?:\|([^}]+))?\}\}")
UNSUBSTITUTED_PATTERN = re.compile(r"\{\{stats:[^}]+\}\}")
GENERATED_HEADER = (
    "<!-- This file is generated by render_page.py from index.template.html "
    "and stats.json; do not edit directly. -->"
)


class RenderError(Exception):
    """Raised when rendering cannot complete safely."""


def resolve_path(data: dict[str, Any], path: str) -> Any:
    """Resolve a dotted path into nested dictionaries."""
    cursor: Any = data
    for segment in path.split("."):
        if not isinstance(cursor, dict) or segment not in cursor:
            raise RenderError(f"Token path not found for '{{{{stats:{path}}}}}'.")
        cursor = cursor[segment]
    return cursor


def apply_format(value: Any, fmt: str | None, token_text: str) -> str:
    """Render values according to optional token format."""
    if fmt is None:
        return str(value)

    if fmt == "p":
        if not isinstance(value, (int, float)):
            raise RenderError(f"Token '{token_text}' uses '|p' but value is not numeric.")
        return f"{value * 100:.1f}"

    if fmt in {"0", "1", "2", "3"}:
        if not isinstance(value, (int, float)):
            raise RenderError(
                f"Token '{token_text}' uses '|{fmt}' but value is not numeric."
            )
        return f"{value:.{int(fmt)}f}"

    raise RenderError(f"Token '{token_text}' has invalid format specifier '{fmt}'.")


def render(template: str, stats: dict[str, Any]) -> tuple[str, list[tuple[str, str]]]:
    """Render template content and return substitutions made."""
    substitutions: list[tuple[str, str]] = []

    def replacer(match: re.Match[str]) -> str:
        token_text = match.group(0)
        path = match.group(1)
        fmt = match.group(2)

        resolved = resolve_path(stats, path)
        rendered = apply_format(resolved, fmt, token_text)
        substitutions.append((token_text, rendered))
        return rendered

    rendered = TOKEN_PATTERN.sub(replacer, template)

    remaining = UNSUBSTITUTED_PATTERN.findall(rendered)
    if remaining:
        raise RenderError(
            "Unsubstituted token(s) remain after rendering: " + ", ".join(remaining)
        )

    return rendered, substitutions


def main() -> int:
    try:
        if not STATS_PATH.exists():
            raise RenderError(
                "Missing stats.json. Run colorado_snowpack_enso.py first to generate it."
            )

        if not TEMPLATE_PATH.exists():
            raise RenderError("Missing index.template.html.")

        with STATS_PATH.open("r", encoding="utf-8") as fh:
            stats = json.load(fh)

        template = TEMPLATE_PATH.read_text(encoding="utf-8")
        rendered_body, substitutions = render(template, stats)

        OUTPUT_PATH.write_text(
            GENERATED_HEADER + "\n" + rendered_body,
            encoding="utf-8",
        )

        print("Token substitution summary:")
        for token, value in substitutions:
            print(f"- {token} -> {value}")
        print(f"Total tokens: {len(substitutions)}")
        print(f"Wrote {OUTPUT_PATH}")
        return 0

    except (OSError, json.JSONDecodeError, RenderError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
